modLoader="javafml"
loaderVersion="[37,)"
license="LGPL"
issueTrackerURL="https://github.com/DarkShadow44/projectbabelfish/issues"
[[mods]] #mandatory
modId="projectbabelfish"
version="${file.jarVersion}
displayName="Project Babelfish"
authors="DarkShadow44"
description='''
TODO
'''
